# Generated by Django 2.0.3 on 2018-03-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180319_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=None, related_name='messages', to='chat.Chat'),
        ),
    ]
