# Generated by Django 2.0.3 on 2018-03-30 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20180319_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
