version: '2'

volumes:
  redisdata:

services:
  redis:
    image: redis:4.0.9
    volumes:
      - 'redisdata:/data'
  messenger:
    image: messenger
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
        - /home/demonizer/projects/security/messenger:/root/messenger
    environment:
      - REDIST_HOST=redis
    links:
      - redis